name: Utils
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches:
      - master
    paths:
      - 'packages/utils/**'
      - '.github/workflows/utils.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/utils/**'
      - '.github/workflows/utils.yml'
      - 'pnpm-lock.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 7.0.x
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -r --filter @web3-storage/worker-utils run lint
      - run: pnpm -r --filter @web3-storage/worker-utils run test
  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
  publish:
    needs: release
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && needs.release.outputs.releases_created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 7.0.x
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -r --filter @web3-storage/worker-utils exec tsc
      - run: pnpm -r --filter @web3-storage/worker-utils publish --tag next --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
